### ISSUE TITLE
DEV backend pointing to PROD Forest Client

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#68]
Backend is configured to point to the Forest Client API in PROD.  This is obscenely bad for development, since changes need to go all the way to production before they can be properly tested.

Worse still, this appears to have been configured MANUALLY so the problem could not be uncovered with a search.

https://console.apps.silver.devops.gov.bc.ca/k8s/ns/b9d53b-dev/secrets/nr-spar-backend

```
data:
  allowed_origins: http://localhost:300*,https://*.apps.silver.devops.gov.bc.ca
  forest-client-api.address: https://nr-forest-client-api-prod.api.gov.bc.ca/api
  forest-client-api.key: <REDACTED>
  keycloak-realm-url: https://test.loginproxy.gov.bc.ca/auth/realms/standard
```
