### ISSUE TITLE
DEV backend using Test Keycloak

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#69]
DEV backends are configured to point to Test Keycloak.  This isn't as bad as where DEV pointed to PROD Oracle API, but still not desirable.

As before, this appears to have been configured MANUALLY so the problem could not be uncovered with a search.

https://console.apps.silver.devops.gov.bc.ca/k8s/ns/b9d53b-dev/secrets/nr-spar-backend

```
data:
  allowed_origins: http://localhost:300*,https://*.apps.silver.devops.gov.bc.ca
  forest-client-api.address: https://nr-forest-client-api-prod.api.gov.bc.ca/api
  forest-client-api.key: <REDACTED>
  keycloak-realm-url: https://test.loginproxy.gov.bc.ca/auth/realms/standard
```
